// Generated by CoffeeScript 1.4.0
(function() {
  var init, loadScript,
    _this = this;

  loadScript = function() {
    var moduleId, script, scriptId, t;
    moduleId = $pz.module.id;
    t = new Date().getTime();
    scriptId = "draw_script";
    $("#" + scriptId).remove();
    script = $("<script>", {
      id: scriptId,
      src: ("puzlet/source.php?pageId=" + moduleId + "&file=draw.js&t=") + t
    });
    $(document.head).append(script);
    return window.$setupDrawing();
  };

  init = function() {
    window.$setupDrawing();
    return $pz.event.codeSaved.on((function(d) {
      return loadScript();
    }));
  };

  puzletInit.register((function() {
    return init();
  }));

}).call(this);
