// Generated by CoffeeScript 1.4.0
(function() {

  $pz.resources = function() {
    return [
      {
        moduleId: "b0088",
        file: "drawing.js"
      }, {
        file: "draw.js"
      }, {
        url: "/puzlet/custom/custom.js"
      }, {
        url: "http://jashkenas.github.io/" + "coffee-script/extras/coffee-script.js"
      }, {
        url: "/jslib/vkbeautify.0.99.00.beta.js"
      }
    ];
  };

}).call(this);
